---
- name: Checking Mariadb containers
  import_role:
    role: service-check

- name: Wait for MariaDB service to be ready through VIP
  become: true
  command: >
    {{ kolla_container_engine }} exec {{ mariadb_service.container_name }}
    mariadb -h {{ database_address }} -P {{ database_port }}
    -u {{ mariadb_shard_database_user }} -p{{ database_password }} -e 'show databases;'
  register: result
  until: result is success
  changed_when: False
  retries: 6
  delay: 10
  when: mariadb_shard_id == mariadb_default_database_shard_id
