---
- import_tasks: config.yml

- import_tasks: check-containers.yml

- import_tasks: recover_cluster.yml
  vars:
    mariadb_cluster_exists: true
  when: migration_flag is defined

- import_tasks: bootstrap.yml
