---
features:
  - |
    Deploys and configures the prometheus-libvirt-exporter image as
    (https://github.com/kumina/libvirt_exporter) as part of the
    Prometheus monitoring stack.
upgrade:
  - |
    The libvirt sockets in the Nova libvirt container have been moved to a
    docker volume to support monitoring of libvirt. As part of this upgrade
    the Nova libvirt containers will be restarted. This will affect users
    of instances running in those containers.
