---
features:
  - |
    Updates Prometheus version to v3.2.1.
upgrade:
  - |
    Prometheus will be upgraded from v2 to v3 - which introduces minor breaking
    changes. Make sure there's version 2.5.5 or later running before attempting
    an upgrade. Read the official migration guide for more details here:
    https://prometheus.io/docs/prometheus/3.0/migration/. Container's name and
    volume name change back to simply ``prometheus_server`` and ``prometheus``,
    respectively. The upgrade preserves the old data from ``prometheus_v2``
    volume, but will leave it behind if the volume name has been customised by
    the operator.
