---
- name: Remove OVS bridges from neutron
  become: true
  command: >
    {{ current_engine }} exec -u root neutron_openvswitch_agent neutron-ovs-cleanup
    --config-file /etc/neutron/neutron.conf
    --config-file /etc/neutron/plugins/ml2/openvswitch_agent.ini
    --ovs_all_ports

- name: Remove OVS bridges
  become: true
  command: >
    {{ current_engine }} exec openvswitch_vswitchd
    bash -c 'for br in `ovs-vsctl list-br`;do ovs-vsctl --if-exists del-br $br;done'
