---
- name: Check telegraf containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    pid_mode: "{{ item.value.pid_mode }}"
    dimensions: "{{ item.value.dimensions }}"
  with_dict: "{{ telegraf_services | select_services_enabled_and_mapped_to_host }}"
  notify:
    - "Restart {{ item.key }} container"
