---
grafana_services:
  grafana:
    container_name: grafana
    group: grafana
    enabled: true
    image: "{{ grafana_image_full }}"
    volumes: "{{ grafana_default_volumes + grafana_extra_volumes }}"
    dimensions: "{{ grafana_dimensions }}"
    haproxy:
      grafana_server:
        enabled: "{{ enable_grafana }}"
        mode: "http"
        external: false
        port: "{{ grafana_server_port }}"
        listen_port: "{{ grafana_server_listen_port }}"
      grafana_server_external:
        enabled: "{{ enable_grafana_external | bool }}"
        mode: "http"
        external: true
        external_fqdn: "{{ grafana_external_fqdn }}"
        port: "{{ grafana_server_public_port }}"
        listen_port: "{{ grafana_server_listen_port }}"

####################
# Database
####################
grafana_database_name: "grafana"
grafana_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}grafana{% endif %}"
grafana_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"

####################
# Datasource
####################
grafana_data_sources:
  influxdb:
    enabled: "{{ enable_influxdb | bool }}"
    data:
      isDefault: yes
      database: "telegraf"
      name: "telegraf"
      type: "influxdb"
      url: "{{ influxdb_internal_endpoint }}"
      access: "proxy"
      basicAuth: false
  elasticsearch:
    enabled: "{{ enable_elasticsearch | bool }}"
    data:
      name: "elasticsearch"
      type: "elasticsearch"
      access: "proxy"
      url: "{{ elasticsearch_internal_endpoint }}"
      database: "flog-*"
      jsonData:
        esVersion: 5
        timeField: "@timestamp"
  opensearch:
    enabled: "{{ enable_opensearch | bool }}"
    data:
      name: "opensearch"
      type: "grafana-opensearch-datasource"
      access: "proxy"
      url: "{{ opensearch_internal_endpoint }}"
      jsonData:
        flavor: "elasticsearch"
        database: "[flog-]YYYY.MM.DD"
        version: "7.0.0"
        timeField: "@timestamp"
  monasca:
    enabled: "{{ enable_monasca | bool }}"
    data:
      name: "Monasca"
      type: "monasca-datasource"
      access: "proxy"
      url: "{{ monasca_api_internal_base_endpoint }}"
      jsonData:
        keystoneAuth: True

##########
# Grafana
##########
grafana_install_type: "{{ kolla_install_type }}"
grafana_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ grafana_install_type }}-grafana"
grafana_tag: "{{ openstack_tag }}"
grafana_image_full: "{{ grafana_image }}:{{ grafana_tag }}"
grafana_admin_username: "admin"

grafana_dimensions: "{{ default_container_dimensions }}"
grafana_default_volumes:
  - "{{ node_config_directory }}/grafana/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "grafana_dashboards:/var/lib/grafana/dashboards"
  - "kolla_logs:/var/log/kolla/"
grafana_extra_volumes: "{{ default_extra_volumes }}"

grafana_start_first_node_delay: 10
grafana_start_first_node_retries: 12

# TODO(dawudm): make this True in the D release
grafana_remove_old_volume: false

############
# Prometheus
############
grafana_prometheus_url: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ prometheus_port }}"
