---
# List of names of containers to check that are enabled and mapped to this
# host.
# TODO(mnasiadka): Add support for iterated containers (e.g. ovn_sb_db_relay)
service_check_enabled_container_names: >-
  {{ lookup('vars', (kolla_role_name | default(project_name)) + '_services') |
     select_services_enabled_and_mapped_to_host |
     dict2items |
     rejectattr('value.iterate', 'defined') |
     map(attribute='value.container_name') |
     list }}
