---
- name: Check masakari containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    ipc_mode: "{{ item.value.ipc_mode | default(omit) }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
  with_dict: "{{ masakari_services | select_services_enabled_and_mapped_to_host }}"
  notify:
    - Restart {{ item.key }} container
