---
ansible_python_interpreter: >-
  {{
    virtualenv ~ '/bin/python'
    if virtualenv is defined
      and virtualenv is not none
      and virtualenv | length > 0
    else (
      ansible_facts.python.executable
      if ansible_facts.python.executable is defined
        and ansible_facts.python.executable is not none
        and ansible_facts.python.executable | length > 0
      else 'auto_silent'
    )
  }}
