---
- name: Check ironic containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    cap_add: "{{ item.value.cap_add | default([]) }}"
    environment: "{{ item.value.environment | default(omit) }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
  with_dict: "{{ ironic_services | select_services_enabled_and_mapped_to_host }}"
  notify:
    - "Restart {{ item.key }} container"
