---
- name: Get container facts
  kolla_container_facts:
    name: "{{ monasca_services.values()|map(attribute='container_name')|list }}"
  register: container_facts

- name: Checking free port for monasca-api
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ monasca_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[monasca_services['monasca-api']['group']]
    - container_facts['monasca_api'] is not defined

- name: Checking free port for monasca-log-api
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ monasca_log_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[monasca_services['monasca-log-api']['group']]
    - container_facts['monasca_log_api'] is not defined

- name: Checking free port for monasca-agent-forwarder
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ monasca_agent_forwarder_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[monasca_services['monasca-agent-forwarder']['group']]
    - container_facts['monasca_agent_forwarder'] is not defined

- name: Checking free port for monasca-agent-statsd
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ monasca_agent_statsd_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[monasca_services['monasca-agent-statsd']['group']]
    - container_facts['monasca_agent_statsd'] is not defined
