---
- include_tasks: register.yml
  when: inventory_hostname in groups['caso']

- include_tasks: config.yml
  when: inventory_hostname in groups['caso']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: check.yml
  when: inventory_hostname in groups['caso']
