---
- name: Pulling caso images
  become: true
  kolla_container:
    container_engine: "{{ kolla_container_engine }}"
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ item.value.image }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ caso_services }}"
