---
- name: Configure cASO user
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "{{ item }}"
      user: "{{ caso_keystone_user }}"
      password: "{{ caso_keystone_password }}"
      region_name: "{{ openstack_region_name }}"
      role: admin
      auth: "{{ caso_openstack_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  with_items: "{{ caso_projects }}"
  run_once: True
