---
- name: Check cinder containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    tmpfs: "{{ item.value.tmpfs | default(omit) }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    ipc_mode: "{{ item.value.ipc_mode | default('') }}"
  with_dict: "{{ cinder_services | select_services_enabled_and_mapped_to_host }}"
  notify:
    - "Restart {{ item.key }} container"
