---
- name: Template out octavia-openrc.sh
  become: "{{ octavia_openrc_become | bool }}"
  template:
    src: octavia-openrc.sh.j2
    dest: "{{ node_config }}/octavia-openrc.sh"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0600
