---
- name: Checking for any existing OVN DB container volumes
  become: true
  kolla_container_volume_facts:
    container_engine: "docker"
    name:
      - ovn_nb_db
      - ovn_sb_db
  register: ovn_db_container_volume_facts

- name: Divide hosts by their OVN NB volume availability
  group_by:
    key: "ovn-nb-db_had_volume_{{ ovn_db_container_volume_facts['ovn_nb_db'] is defined }}"
  changed_when: false

- name: Divide hosts by their OVN SB volume availability
  group_by:
    key: "ovn-sb-db_had_volume_{{ ovn_db_container_volume_facts['ovn_sb_db'] is defined }}"
  changed_when: false

- name: Establish whether the cluster has already existed
  set_fact:
    ovn_nb_db_cluster_exists: "{{ groups['ovn-nb-db' + '_had_volume_True'] is defined }}"

- name: Establish whether the cluster has already existed
  set_fact:
    ovn_sb_db_cluster_exists: "{{ groups['ovn-sb-db' + '_had_volume_True'] is defined }}"

- name: OVN NB checks
  block:

    - name: Check OVN NB service port liveness
      wait_for:
        host: "{{ api_interface_address }}"
        port: "{{ ovn_nb_db_port }}"
        connect_timeout: 1
        timeout: 10
      register: check_ovn_nb_db_port_liveness
      ignore_errors: yes

    - name: Divide hosts by their OVN NB service port liveness
      group_by:
        key: "ovn-nb-db_port_alive_{{ check_ovn_nb_db_port_liveness is success }}"
      changed_when: false

    - name: Fail on existing but stopped NB cluster
      fail:
        msg: OVN NB cluster node exists but is stopped - please start it.
      when:
        - ovn_nb_db_cluster_exists
        - inventory_hostname in groups['ovn-nb-db' + '_had_volume_True']
        - groups['ovn-nb-db' + '_port_alive_True'] is not defined

    - name: Get OVN NB database information
      command: 'docker exec ovn_nb_db ovsdb-client query unix:/run/ovn/ovnnb_db.sock "[\"_Server\",{\"table\":\"Database\",\"where\":[[\"name\",\"==\", \"OVN_Northbound\"]],\"op\":\"select\"}]"'
      become: true
      changed_when: false
      register: ovn_nb_db_info

    - name: Divide hosts by their OVN NB leader/follower role
      group_by:
        key: "ovn-nb-db_{{ 'leader' if (ovn_nb_db_info.stdout | from_json).0.rows.0.leader else 'follower' }}"
      changed_when: false

  any_errors_fatal: true
  when: inventory_hostname in groups.get('ovn-nb-db_had_volume_True', '')

- name: OVN SB checks
  block:

    - name: Check OVN SB service port liveness
      wait_for:
        host: "{{ api_interface_address }}"
        port: "{{ ovn_sb_db_port }}"
        connect_timeout: 1
        timeout: 10
      register: check_ovn_sb_db_port_liveness
      ignore_errors: yes

    - name: Divide hosts by their OVN SB service port liveness
      group_by:
        key: "ovn-sb-db_port_alive_{{ check_ovn_sb_db_port_liveness is success }}"
      changed_when: false

    - name: Fail on existing but stopped SB cluster
      fail:
        msg: OVN SB cluster node exists but is stopped - please start it.
      when:
        - ovn_sb_db_cluster_exists
        - inventory_hostname in groups['ovn-sb-db' + '_had_volume_True']
        - groups['ovn-sb-db' + '_port_alive_True'] is not defined

    - name: Get OVN SB database information
      command: 'docker exec ovn_sb_db ovsdb-client query unix:/run/ovn/ovnsb_db.sock "[\"_Server\",{\"table\":\"Database\",\"where\":[[\"name\",\"==\", \"OVN_Southbound\"]],\"op\":\"select\"}]"'
      become: true
      changed_when: false
      register: ovn_sb_db_info

    - name: Divide hosts by their OVN SB leader/follower role
      group_by:
        key: "ovn-sb-db_{{ 'leader' if (ovn_sb_db_info.stdout | from_json).0.rows.0.leader else 'follower' }}"
      changed_when: false

  any_errors_fatal: true
  when: inventory_hostname in groups.get('ovn-sb-db_had_volume_True', '')
