---
- name: Check zun containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
  with_dict: "{{ zun_services | select_services_enabled_and_mapped_to_host }}"
  notify:
    # NOTE(yoctozepto): Zun differs from other projects because we want
    # to differentiate between config change and container property
    # change
    - "{{ item.key }} container changed"
