---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-podman
        - kolla-ansible-ubuntu
        - kolla-ansible-ubuntu-podman
        - kolla-ansible-ubuntu-kvm
        - kolla-ansible-ubuntu-multinode-ipv6
        - kolla-ansible-ubuntu-bifrost
        - kolla-ansible-ubuntu-zun
        - kolla-ansible-ubuntu-magnum
        - kolla-ansible-ubuntu-octavia
        - kolla-ansible-ubuntu-masakari
        - kolla-ansible-debian-ironic
        - kolla-ansible-ubuntu-ironic
        - kolla-ansible-debian-upgrade
        - kolla-ansible-ubuntu-upgrade
        - kolla-ansible-ubuntu-cells
        - kolla-ansible-debian-mariadb
        - kolla-ansible-ubuntu-mariadb
        - kolla-ansible-debian-ovn
        - kolla-ansible-ubuntu-ovn
        - kolla-ansible-debian-upgrade-ovn
        - kolla-ansible-ubuntu-upgrade-ovn
        - kolla-ansible-debian
        - kolla-ansible-ubuntu-prometheus-opensearch
        - kolla-ansible-ubuntu-prometheus-opensearch-upgrade
        - kolla-ansible-ubuntu-venus
        - kolla-ansible-ubuntu-cephadm
        - kolla-ansible-ubuntu-upgrade-cephadm
        - kolla-ansible-ubuntu-haproxy-fqdn
        - kolla-ansible-ubuntu-lets-encrypt
        - kolla-ansible-ubuntu-skyline
        - kolla-ansible-ubuntu-skyline-sso
        - kolla-ansible-ubuntu-container-engine-migration
        - kolla-ansible-ubuntu-container-engine-migration-multinode
        - kolla-ansible-debian-container-engine-migration
        - kolla-ansible-debian-container-engine-migration-multinode
    check-arm64:
      jobs:
        - kolla-ansible-debian-aarch64
        - kolla-ansible-debian-aarch64-podman
        - kolla-ansible-debian-upgrade-aarch64
    gate:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-mariadb
        - kolla-ansible-debian-upgrade
        - kolla-ansible-debian-podman
        - kolla-ansible-ubuntu
        - kolla-ansible-ubuntu-mariadb
        - kolla-ansible-ubuntu-prometheus-opensearch
        - kolla-ansible-ubuntu-prometheus-opensearch-upgrade
        - kolla-ansible-ubuntu-upgrade
        - kolla-ansible-ubuntu-podman
